export const data = {
  type: "feature",
  features: [
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-77.0317, 38.9146] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 1",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Black Cat",
        cluster: false,
        venue: "blackcat",
        event_count: 10,
      },
    },
    {
      type: "Feature",
      geometry: { type: "truck", coordinates: [-77.023982, 38.878824] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 2",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Pearl Street Warehouse",
        cluster: false,
        venue: "pearlstreet",
        event_count: 2,
      },
    },
    {
      type: "Feature",
      geometry: { type: "bus", coordinates: [-77.0423, 38.9224] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 3",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Songbyrd Cafe",
        cluster: false,
        venue: "songbyrd",
        event_count: 10,
      },
    },
    {
      type: "Feature",
      geometry: { type: "Train", coordinates: [-77.0317, 38.9028] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 4",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "The Hamilton",
        cluster: false,
        venue: "thehamilton",
        event_count: 9,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-76.9859, 38.9144] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 5",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "City Winery",
        cluster: false,
        venue: "citywinery",
        event_count: 9,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-77.0241, 38.8787] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 6",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Union Stage",
        cluster: false,
        venue: "unionstage",
        event_count: 24,
      },
    },
    {
      type: "Feature",
      geometry: { type: "truck", coordinates: [-77.0292, 38.8965] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 7",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Warner Theatre",
        cluster: false,
        venue: "warnertheatre",
        event_count: 19,
      },
    },
    {
      type: "Feature",
      geometry: { type: "bus", coordinates: [-77.0242, 38.9168] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 8",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "DC9 Nightclub",
        cluster: false,
        venue: "dc9",
        event_count: 2,
      },
    },
    {
      type: "Feature",
      geometry: { type: "bus", coordinates: [-76.9869, 38.9] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 9",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Pie Shop",
        cluster: false,
        venue: "pieshop",
        event_count: 8,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-77.0237, 38.9179] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 10",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "9:30 Club",
        cluster: false,
        venue: "_930",
        event_count: 25,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-77.0211, 38.9154] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 11",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "The Howard Theatre",
        cluster: false,
        venue: "thehowardtheatre",
        event_count: 8,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-77.0277, 38.9172] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car  12",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "U Street Music Hall",
        cluster: false,
        venue: "ustreet",
        event_count: 11,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-76.9726, 38.9198] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 13",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Echo Stage",
        cluster: false,
        venue: "echostage",
        event_count: 2,
      },
    },
    {
      type: "Feature",
      geometry: { type: "bus", coordinates: [-77.0291, 38.9171] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car 14",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Lincoln Theatre",
        cluster: false,
        venue: "lincolntheatre",
        event_count: 17,
      },
    },
    {
      type: "Feature",
      geometry: { type: "bus", coordinates: [-77.0255, 38.8804] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "The Anthem",
        cluster: false,
        venue: "theanthem",
        event_count: 26,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-77.0557, 38.8958] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "The Kennedy Center",
        cluster: false,
        venue: "kennedycenter",
        event_count: 230,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-76.995134, 38.881679] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Miracle Theatre",
        cluster: false,
        venue: "miracletheatre",
        event_count: 1,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-77.0221, 38.8951] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Hill Country",
        cluster: false,
        venue: "hillcountry",
        event_count: 2,
      },
    },
    {
      type: "Feature",
      geometry: { type: "car", coordinates: [-77.007433, 38.87301] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Nationals Park",
        cluster: false,
        venue: "nationalspark",
        event_count: 4,
      },
    },
    {
      type: "Feature",
      geometry: { type: "bus", coordinates: [-77.02088, 38.898125] },
      youtubeURL: "https://www.youtube.com/embed/R93ce4FZGbc?si=GAJEgZf0AHmIY7sr",
      title: "this is a car",
      payload: [
        { key: "Car number:", value: "11223 112 12" },
        { key: "Localisation:", value: "36.7785611.562 - Hidra - Alger" },
        { key: "Velocity:", value: "45km/h" },
      ],
      properties: {
        title: "Capital One Arena",
        cluster: false,
        venue: "capitaloneconcerts",
        event_count: 7,
      },
    },
  ],
};
